### ISSUE TITLE
Multiple pause/play

### ISSUE THREAD

**Issue by tigermick** [icefields/Power-Ampache-2#152] opened 2024-08-28 21:00 UTC
Hi,
First of all, thanks for your great app. This is a very beautiful music app !
But I have a problem with it.
I have a nextcloud server with music app enable and all works fine with ultrasonic app.
However, I prefer your new app !
If i try to play music, sometimes all work fine and sometimes, I have lot of lag during to play music ...
Someone  already saw this problem please ?

**Comment by CrazyStevenz** [comment] 2024-08-29 11:25
Seems like a duplicate of #148.

**Comment by tigermick** [comment] 2024-08-29 11:37
But I just have mp3 files ...

**Comment by CrazyStevenz** [comment] 2024-08-29 11:51
Yeah, we figured out in that issue that it's not the flac files causing it, will ask to remove it from the title. Does this issue happen for you in offline mode (which can be enabled in the Settings, or in the navbar if you don't have an internet connection), or are you always online?

**Comment by icefields** [comment] 2024-08-30 19:30
@tigermick Thanks for the report. 
This a duplicate, the title of the other issue was wrong, it's not only for flac files, and happens both online and offline. 
I'm going to close, please continue the conversation in the other thread. https://github.com/icefields/Power-Ampache-2/issues/148

**Closed by icefields** 2024-08-30 19:30 UTC
