### ISSUE TITLE
Freezes on first launch

### ISSUE THREAD

**Issue by ef1f** [icefields/Power-Ampache-2#137] opened 2024-07-04 08:39 UTC
Freezes on first launch on a device with Android 10
![freez](https://github.com/icefields/Power-Ampache-2/assets/45484701/e1b0d8b5-1811-428e-a1f5-8b7d03dddde0)

**Comment by icefields** [comment] 2024-07-05 00:27
the fix is in version 1.00-62, available here : https://github.com/icefields/Power-Ampache-2/releases/tag/v1.00-62 
Or on [FDroid](https://f-droid.org/packages/luci.sixsixsix.powerampache2.fdroid) in 4-5 days.

**Comment by icefields** [comment] 2024-07-15 22:12
hello, I'd like to close this issue, can you confirm the issue is fixed?

ps. You might like to know that the next release (1.00-64) is going to have some landscape-mode improvements

**Comment by ef1f** [comment] 2024-07-16 04:54
Thank you, issue is fixed.

**Closed** 2024-07-16 04:55 UTC
