### ISSUE TITLE
When playing a song from the middle of an album the next song in the album is not played 

### ISSUE THREAD

**Issue by meldarionqeusse** [icefields/Power-Ampache-2#165] opened 2024-11-29 06:55 UTC
Probably title does not explain my issue clearly hope I can make it clear here.

I usually like listening to albums in their entirety  so my mind is wired to think about albums not playlist or whatever random stuff streaming services try to invent. 

Occasionally however I want to play tracks 4, 5and 6 for example of an album. So I go to the album tap on track 4 and after it finishes I expect track 5 to play instead I am getting random songs from totally unreleated artists. 

Is it possible to have playback to be somehow set to album focused? 
Not sure if there is a settings options honestly power ampache has son many options I get lost in them but I love it is so clean and straightforward ny issue here is just one minor annoyance that would make the app perfect for me. 

Thank you

**Comment by icefields** [comment] 2024-11-29 16:01
hello @meldarionqeusse this sounds like a bug, thanks for pointing it out. I'll be working on PA2 today, so you might get a fix for this in the upcoming release.
Just to be more precise, can you provide the steps to reproduce the bug? If I understood correctly, those should be the steps, correct me if I'm wrong:
- user taps on an albums and navigates to the album screen
- user plays a random song in the album (not the first one), for example song 4
- when the song finishes, instead of going to song 5, it plays the beginning of the album.
Expected behaviour: when song 4 finishes, it should play song 5, then 6, etc ... in succession.
Conditions: you are in the album view, the random-album button is off, the random player button is set to off.

This is my experience while testing your bug. There is definitely a bug, what is throwing me off is the part where you say "I am getting random songs from totally unreleated artists.", I cannot reproduce this on my installation.
Check out this video of the bug on my side (don't mind the debug-ui), as you can see, after turning the random buttons off, I start by playing "Weaponized Loss", the next song should be "Flood of Predation", but when I visualize the queue, you'll see that the app is basically restarting the album instead of having the next song in succession.


https://github.com/user-attachments/assets/535dabf9-5a39-4218-9e74-9afd40c5266b

**Comment by meldarionqeusse** [comment] 2024-11-29 16:31
Hi thanks for replying and confirming the bug.

So the reason i was getting "random artist" was because it had the previous queue loaded and it was playing the song I select and then continues to play from the previous queue. If I clear the queue I get what you explained it starts from the beginning of the album.

Took some screen caps but am on mobile cannot upload atm cause they are too large. But if you need a video to understand better what I mean I can try to find some time and upload tomorrow.

**Comment by icefields** [comment] 2024-11-29 16:50
thanks for the quick reply. 
You confirmed that we're talking about the same bug and my steps to reproduce are correct. That's enough for me to fix the bug. I will try to include it in the next release `1.00-70` .
Thanks!

**Comment by meldarionqeusse** [comment] 2024-11-29 17:10
Looks forward for next release and thanks for your work

**Comment by icefields** [comment] 2024-11-29 23:10
Fix done. I wonder why no one reported this before.
I plan on making the release this weekend.

https://github.com/user-attachments/assets/46dbcfe5-554a-4fdb-a6b3-e023b934d9b3

**Comment by meldarionqeusse** [comment] 2024-11-30 06:16
Perfect thank you for the fixing it so quickly.

From my own personal experience. I still buy physical CDs and when my colleagues realise they are amazed and I always ask how they listen to music which is spotify but then I specifically ask if they ever listened to a complete album or just singles and predominately it's singles and playlists. So probably this was not a common user interaction plus if it happened they probably wouldn't realise because they got used to music being played randomly.

**Comment by icefields** [comment] 2024-12-01 01:25
CDs are cool, I usually just buy my music on Bandcamp, but sometime I get CDs too. Last month I bought some cool albums in Japan, all japanese editions. I know that on average, people only listen to single songs, so you're probably right

**Closed** 2024-12-06 15:27 UTC
