### ISSUE TITLE
Can´t connect to Nextcloud Music V1.11 with regular user

### ISSUE THREAD

**Issue by TaKouMyS** [icefields/Power-Ampache-2#117] opened 2024-05-24 13:19 UTC
Hello there and thanks for your work :)

I apologize in advance if this is due to a mistake on my side but I thought it might be a bug as the release is kind of new.

I just set up [OwnCloud music](https://github.com/owncloud/music) on my Nextcloud instance, it runs le latest version `v1.11` wich runs ampache API v6.

I can connect with [Power Ampache ](https://f-droid.org/packages/com.antoniotari.reactiveampacheapp/) from f-droid but with Power-Ampache-2, APK download from `v1.00-55` release page (f-droid build and github build) every time I try to connect it says : 
`Invalid login - passphrase does not match`

I am using keepass to enter the url, login and password so I am pretty sure credentials are corrects

Could it be a bug in Power-Ampache-2 ? How can I get further logs ? 
(My nextcloud logs don't show any unsuccesful login attempts) 

Thanks for your time!

Edit : Maybe it is relevant to say that I run CalyxOS without google play services...

**Comment by icefields** [comment] 2024-05-24 13:46
Hello,
thanks for reporting a potential bug.
Device is not an issue, I test every release on CalyxOS and GrapheneOS (without play services).<br>
Few things to try:
- Can you try to login with admin? Some user have reported permission issues with the Nexcloud backend when using regular users (this might be a mistake on their end, I haven't digged into the issue yet).
- Does the dogmazic server work? (so we can rule out a potential app problem)
- Are you using a custom port? (add the port to the address)
- Are you using a self signed certificate with https? (android doesn't allow this)
- are you adding http:// if you don't have a certificate? (shouldn't be necessary if you're using ip addresses, but try anyway)
<br>
**This is how I login into Nextcloud when I test:**

![photo_2024-05-24_09-36-57](https://github.com/icefields/Power-Ampache-2/assets/149625124/f6321bcd-7be6-4a12-9067-7a00baff045f)

**Comment by TaKouMyS** [comment] 2024-05-24 14:33
Wow thanks for this quick answer!

First point hit, I tried with admin user and it worked

Hard for me to dig more than that, the only lead I have for you is the fact that :
- at least one client can log in using regular accounts(Power Ampache)

Thanks a lot for your time, I you need anything the day you start working on this (if you do) let me know.

**Comment by icefields** [comment] 2024-05-24 14:58
No problem at all, I will have to coordinate with the developer of Nextcloud Music to dig into this issue. And thanks for offering your help!

ps. I just now released a new version here on Github. Also, if you prefer, the app got approved yesterday on FDroid and it's now available there as well. Github and Fdroid versions will be pretty much identical, except for the fact that Github releases will be 3 to 6 days earlier and are signed by me (while FDroid apps are signed by them).

**Comment by TaKouMyS** [comment] 2024-05-24 15:25
Oh nice, congratz for the F-droid publishing \o/

**Comment by icefields** [comment] 2024-05-25 18:25
hey @paulijar , do you have any input about this issue? <br>
3 users so far reported they're not able to login using regular users, everything seem to work fine using admin.
Thanks

**Comment by paulijar** [comment] 2024-05-26 14:16
This really sounds like a server-side issue. However, it's weird because Nextcloud Music doesn't use the user authentication mechanisms provided by Nextcloud. All the Ampache API functions are technically "public" i.e. do not require any Nextcloud user authentication and then we have built our own custom password/API-key system for the authentication. In this context, admin user shouldn't be anyhow different from any other user.

I couldn't reproduce the problem using PA2 v1.00-56 and Music 1.11.0 on Nextcloud 27.1.2 nor on  Nextcloud 29-RC5 (which, I think, is identical with 29.0.0). Which version of Nextcloud are those people with this problem using?

**Comment by icefields** [comment] 2024-05-26 14:34
Thanks for answering promptly,
I'll look into my code as well, @TaKouMyS mentions that login with the old Power Ampache app works ok with non-admin users. The login method is defined in the API spec, and it's the same for both apps, except the old Power Ampache uses XML instead of JSON responses.

from @TaKouMyS initial message:

> I just set up [OwnCloud music](https://github.com/owncloud/music) on my Nextcloud instance, it runs le latest version v1.11 wich runs ampache API v6.
> 
> I can connect with [Power Ampache ](https://f-droid.org/packages/com.antoniotari.reactiveampacheapp/)from f-droid but with Power-Ampache-2, APK download from v1.00-55 release page (f-droid build and github build) every time I try to connect it says :
> Invalid login - passphrase does not match

**Comment by drake-99** [comment] 2024-05-28 13:06
Hi I think I found the root cause 2 days ago but my message was shadow banned by GitHub, I only resolved the issue now.

On my setup, I found that the app sends the login username in lowercase as a GET parameter while Nextcloud's implementation expects it to match the real case.

**Comment by paulijar** [comment] 2024-05-28 20:14
I did some testing and found out that the user names are case insensitive also for the regular access control of both Nextcloud and ownCloud. Hence, it would totally make sense to follow the suite also on the Music Ampache API (as well as in the Subsonic API). I'll change this for the next release of Music.

**Comment by icefields** [comment] 2024-05-28 20:25
that sounds great @paulijar , thanks!

**Comment by SamuXzX** [comment] 2024-06-02 14:23
Sorry to bother, but reading the thread I didn't get if this issue can be reliably solved by thinkering in Nextcloud's database or if I can wait for an update in the app.
I too cannot login into my Nextcloud Music instance with Power Ampache 2. I tried providing the username in lowercase (as the first letter of my Nextcloud username is uppercase) but nothing changes. Also, my Nextcloud account is a root one.

**Comment by paulijar** [comment] 2024-06-02 19:13
@SamuXzX The current status of this is that the login cannot work if your username on Nextcloud contains any upper case letters. Either the client or the server needs a fix before this can work. The server-side fix already exists but I haven't decided yet the time of the next release.

But I would also argue that what the Power Ampache 2 client does here, is kind of wrong. The username should be passed to the server exactly like the user gave it. Otherwise the client is depending on an undocumented behavior.

**Comment by SamuXzX** [comment] 2024-06-02 20:36
For sure Power Ampache 2 is relying on a faulty mechanism; given that this mechanism is being fixed, this app should follow.
Thanks to the both of you.

**Comment by icefields** [comment] 2024-06-02 20:39
@SamuXzX Right now usernames that were registered containing uppercase letters will not work with Nextcloud Music / Power Ampache 2. As soon as @paulijar enhancement is deployed it should work as soon as you update Music. 
For now what you can do is login with `admin` , or create a lowercase username to use with Power Ampache 2, like `mylowercaseusername`.

> But I would also argue that what the Power Ampache 2 client does here, is kind of wrong. The username should be passed to the server exactly like the user gave it. Otherwise the client is depending on an undocumented behavior.
> 
Yes, it is architecturally incorrect, I realize now. The rationale behind this approach lies in using the username as a key for various purposes (including multi-user features currently in development, and user settings). I opted to convert the username to lowercase upon login and save it that way, rather than calling lower(username) each time I needed it, to minimize potential bugs. I consulted with the developers of Ampache regarding this decision, though I hadn't tested it on Nextcloud at the time. Rectifying this issue would require a significant refactor and thorough testing. Alternatively, I could consider adding an extra column, realCaseUsername, to the user table and utilizing it for network calls. 

Anyway, in the short-medium term, the fix from @paulijar will solve this problem, keep an eye on the updates from Nextcloud Music.

**Comment by CypLef** [comment] 2024-06-11 14:05
> Hello, thanks for reporting a potential bug. Device is not an issue, I test every release on CalyxOS and GrapheneOS (without play services). Few things to try:
> 
>     * Can you try to login with admin? Some user have reported permission issues with the Nexcloud backend when using regular users (this might be a mistake on their end, I haven't digged into the issue yet).
> 
>     * Does the dogmazic server work? (so we can rule out a potential app problem)
> 
>     * Are you using a custom port? (add the port to the address)
> 
>     * Are you using a self signed certificate with https? (android doesn't allow this)
> 
>     * are you adding http:// if you don't have a certificate? (shouldn't be necessary if you're using ip addresses, but try anyway)
> 
> 
> 
> **This is how I login into Nextcloud when I test:**
> 
> ![photo_2024-05-24_09-36-57](https://private-user-images.githubusercontent.com/149625124/333608521-f6321bcd-7be6-4a12-9067-7a00baff045f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTQ2MTcsIm5iZiI6MTcxODExNDMxNywicGF0aCI6Ii8xNDk2MjUxMjQvMzMzNjA4NTIxLWY2MzIxYmNkLTdiZTYtNGExMi05MDY3LTdhMDBiYWZmMDQ1Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMzU4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDQ4MTAwOGNmYjE5NjNiOWE5NTdlZDJhODY5ZDRkMWYyZTU5OTk3NzBmMzIzYjUxZTY5MzExZTg1YjJmNTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q2xk_-2O4AvNK3elN-Lf6GNbmA8hU4OQqKxvmU2Q7OM)

I have a similar issue : "Cannot connect to your server" but:
- The username is only in lowercase
- I tried both with admin and regular user: both failed (and both are lowercase only username)
- I use Music V1.11 and the latest release of power Ampache on F-droid
- The Ampache API is V6.
- The dogmatize server work
- It doesn't work with the old app "power ampache" as well, but with subsonic it works (app: Ultrasonic)

**Comment by icefields** [comment] 2024-06-11 20:19
@CypLef thanks for the report. 
A couple of notes to start:
- there's an enhancement the developer of Nextcloud Music is working on (not sure the update is out yet) that will fix the username issue, once the update is live you'll be able to login with any username format.
- self signed certificates now work (since 1.00-59)
- The old Power Ampache (1) is not maintained, worth trying maybe, but keep in mind it uses XML responses, on an old API level.

And a couple of questions/requests:
- Do you have any server log of this error?
- are you getting any message on the error view of the login page?
- What's the phone model and the android version?
- If you're comfortable with it, and your server is open to the internet, is it possible for you to give me a temporary account on your server so I can check the android logs in my developer environment? (Contact me privately for that, Telegram, Email or Mastodon)

**Comment by SamuXzX** [comment] 2024-06-11 20:44
> @CypLef thanks for the report. A couple of notes to start:
> 
>     * there's an enhancement the developer of Nextcloud Music is working on (not sure the update is out yet) that will fix the username issue, once the update is live you'll be able to login with any username format.
> 
>     * self signed certificates now work (since 1.00-59)
> 
>     * The old Power Ampache (1) is not maintained, worth trying maybe, but keep in mind it uses XML responses, on an old API level.
> 
> 
> And a couple of questions/requests:
> 
>     * Do you have any server log of this error?
> 
>     * are you getting any message on the error view of the login page?
> 
>     * What's the phone model and the android version?
> 
>     * If you're comfortable with it, and your server is open to the internet, is it possible for you to give me a temporary account on your server so I can check the android logs in my developer environment? (Contact me privately for that, Telegram, Email or Mastodon)

I can help, but I can't find your contacts in your profile.

**Comment by icefields** [comment] 2024-06-12 12:41
telegram: https://t.me/PowerAmpache
mastodon: https://floss.social/@powerampache
email: arctic.icefields @ slmails .com

**Comment by CypLef** [comment] 2024-06-14 12:00
@icefields 

- I can't access the server log ( i'm admin, but i do not host my instance, a superadmin does, and he made something specific for the logs)
- The error message says: "Cannot connect to your server"
- My phone is a fairphone FP2 running on LineageOS 18.1 (Android 11), without Google play Services

**Comment by icefields** [comment] 2024-06-14 13:41
ok thanks @CypLef , if I could have some temporary access it could allow me to check the adb android logs using the app in debug mode, that would greatly speed up the work instead of keep guessing.
email: arctic.icefields @ slmails . com
telegram: https://t.me/PowerAmpache
mastodon: https://floss.social/@powerampache

**Comment by SamuXzX** [comment] 2024-06-15 13:03
@icefields we cannot message you on Telegram, as that is a channel

**Comment by icefields** [comment] 2024-06-15 13:14
> @icefields we cannot message you on Telegram, as that is a channel

@SamuXzX that's true, apparently I'd have to add you manually to the chat, this is my personal contact: https://t.me/plutonEstUnePlanete .

I'll look into creating a chat-room for support and general PA2 chat, I just need to decide if I want to stay on Telegram or move to Matrix. I know there's a Matrix-Telegram bridge, I need to look into all this stuff before deciding.

**Comment by icefields** [comment] 2024-06-17 11:23
> @icefields we cannot message you on Telegram, as that is a channel

hey @SamuXzX , https://t.me/powerampache2 , this is the group chat associated to the channel, it was invitations only before, I now made it public.

**Comment by paulijar** [comment] 2024-06-23 19:40
The case-insensitive username handling has now been released in Nextcloud Music v2.0.0.

**Comment by icefields** [comment] 2024-06-23 19:48
> The case-insensitive username handling has now been released in Nextcloud Music v2.0.0.

that's fantastic news! thanks!

**Comment by mib-2020** [comment] 2024-06-24 08:26
I was hoping that my login problem was related to this issue, so I've been watching this thread for some time. Unfortunately, I still can't log in to my Nextcloud server with PowerAmpache2. 
When I try to log in to my server at the URL https://example.com/apps/music/ampache with my user name (all lower case) and my password, I get the error message "Invalid Login - passphrase does not match". 
Here is my system configuration:

Server:
Nextcloud Hub 8 (29.0.2)
Nextcloud Music Version 2.0.0

Client:
Google Pixel 7a
CalyxOs 5.8.0 (Android 14)
Power-Ampache2 1.00-60-fdroid
I can log in to the Dogmazic Music Server DEMO. 
[Additional info: With Ultrasonic I can log in under the URL https://example.com/apps/music/subsonic with the same credentials]

Any help would be appreciated.

**Comment by SamuXzX** [comment] 2024-06-24 16:42
Maybe you should provide an account on your instance for @icefields, in order to check app logs.

**Comment by icefields** [comment] 2024-06-24 17:11
thanks @SamuXzX , that's what I was about to ask. @mib-2020 If you're comfortable with it, can you create a test account I can use to check the app debug logs from my machine? You can find me in the Telegram group chat https://t.me/powerampache2 or let me know if you prefer email.

**Comment by mib-2020** [comment] 2024-06-24 18:42
I prefer e-mail, because I haven't installed telegram.
Kind regards

24.06.2024 19:12:20 Antonio ***@***.***>:

**Comment by icefields** [comment] 2024-06-25 16:43
> I prefer e-mail, because I haven't installed telegram.

 email: arctic.icefields @ slmails . com

**Comment by mib-2020** [comment] 2024-06-26 19:01
I have sent you credentials for testing via e-mail :-)

**Comment by icefields** [comment] 2024-06-28 19:13
@mib-2020 The error is very odd, it doesn't seem to be related to Power Ampache 2. To prove that, I wrote this script/webpage to verify your handshake call using the credentials you provided to me by email, removing PA2 from the equation (you can test it too, just replace myPassword, myAmpacheServerAddress and myUsername with actual values). 
This is the default procedure specified in the API docs, and it's platform independent, so totally independent from PA2.

```
<?php
    $time = time();
    $key = hash('sha256', '<myPassword>'); 
    $passphrase = hash('sha256', $time . $key);
    $url = ("https://<myNextcloudServerAddress>/apps/music/ampache/server/json.server.php?action=handshake&auth=" . $passphrase . "&user=<myUsername>&timestamp=" . $time);

    header('Location: '.($url));
    die();
?>
```
And I'm getting the same error as you've been getting:
`{"error":{"errorCode":"4701","errorAction":"handshake","errorType":"system","errorMessage":"Invalid Login - passphrase does not match"}}`

The script works without any issue with all my test users, including Nextcloud Music users.
Here's a sample of how it's supposed to look like:
`{"session_expire":"2024-06-28T20:44:50+00:00","auth":"b29dbcc48fb031ac8689dbcc773f","api":"630000","update":"2024-05-26T17:52:38+00:00","add":"2024-05-26T17:52:38+00:00","clean":"2024-06-28T19:04:50+00:00","songs":269,"artists":23,"albums":28,"playlists":3,"searches":1,"playlists_searches":4,"podcasts":0,"podcast_episodes":0,"live_streams":0,"genres":11,"videos":0,"catalogs":0,"shares":0,"licenses":0,"labels":0}`

@lachlan-00 @paulijar  If you validate my test and agree that this issue is independent from PA2, I'll move it into one of your issue trackers.
Thanks

**Comment by paulijar** [comment] 2024-06-28 20:00
Weird, indeed, especially if the same credentials work fine in the Subsonic API. One thing @mib-2020 could do would be to set the logging level on Nextcloud temporarily to `debug`. This can be achieved by editing the file `config/config.php` and adding there the key-value line `'loglevel' => 0,`. Then make another Ampache handshake attempt and see what appears to the file `nextcloud.log`. If nothing else, at least it should then show the URL of the failed handshake attempt as the server received it. We could then see, if the argument `auth` and the others look the same on the server side as on the client side, and no-one has broken them in transit.

**Comment by mib-2020** [comment] 2024-06-29 06:13
I apologise very much. The error had nothing to do with Ampache2 or Nextcloud Music, but with the fact that I had forgotten that I had to use the separate API password instead of the normal nextcloud user credentials. 
As soon as I did  it right, it worked. Thank you very much for your help.

**Closed** 2024-06-29 19:07 UTC
Labels: bug, nextcloud
